name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install and build
        run: |
          npm i -g @nestjs/cli
          npm i
          npm run build
          cp package.json ./dist
          cp package-lock.json ./dist
          cd ./dist && npm i

      - name: SCP upload-prod
        uses: appleboy/scp-action@master
        with:
          host: 43.131.63.37
          username: pincman
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./dist"
          target: "/tmp/miint-api"

      - name: SSH deploy-prod
        uses: appleboy/ssh-action@master
        with:
          host: 43.131.63.37
          username: pincman
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/pincman/htdocs/miint/api && rm -rf /home/pincman/htdocs/miint/api
            mv /tmp/miint-api/dist /home/pincman/htdocs/miint/api
            cd /home/pincman/htdocs/miint/api
            echo "${{ secrets.ENV_VARS }}"
            echo "${{ secrets.ENV_VARS }}" > .env
            rm -rf /tmp/miint-api
            source ~/.zshrc; node ./cli.js dbmr && cd .. && pm2 restart ecosystem.config.js
